// This file is auto-generated by @hey-api/openapi-ts

export const $AuthRequest = {
    type: 'object',
    description: 'API Login and Authorization Request',
    properties: {
        username: {
            type: 'string',
            description: 'Username',
            example: 'admin',
            minLength: 1
        },
        password: {
            type: 'string',
            description: 'Password',
            example: 'admin123',
            maxLength: 2147483647,
            minLength: 6
        }
    },
    required: ['password', 'username']
} as const;

export const $AuthResponse = {
    type: 'object',
    properties: {
        token: {
            type: 'string',
            description: 'JWT Authorization Token',
            example: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJhYmNkMTIzIiwiZXhwaXJ5IjoxNjQ2NjM1NjExMzAxfQ.3Thp81rDFrKXr3WrY1MyMnNK8kKoZBX9lg-JwFznR-M'
        },
        username: {
            type: 'string',
            description: 'Username',
            example: 'admin'
        }
    },
    required: ['token', 'username']
} as const;