// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginData, LoginResponse, GetProtectedResourceResponse, GetPublicResourceResponse, GetAllCollectorsData, GetAllCollectorsResponse, GetCollectorByIdData, GetCollectorByIdResponse } from './types.gen';

export class AuthControllerService {
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns AuthResponse OK
     * @throws ApiError
     */
    public static login(data: LoginData): CancelablePromise<LoginResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/auth/login',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
}

export class ResourceControllerService {
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getProtectedResource(): CancelablePromise<GetProtectedResourceResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/resource'
        });
    }
    
    /**
     * @returns string OK
     * @throws ApiError
     */
    public static getPublicResource(): CancelablePromise<GetPublicResourceResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/public/resource'
        });
    }
    
}

export class CollectorControllerService {
    /**
     * @param data The data for the request.
     * @param data.q
     * @returns Collector OK
     * @throws ApiError
     */
    public static getAllCollectors(data: GetAllCollectorsData = {}): CancelablePromise<GetAllCollectorsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/collectors',
            query: {
                q: data.q
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.id
     * @returns Collector OK
     * @throws ApiError
     */
    public static getCollectorById(data: GetCollectorByIdData): CancelablePromise<GetCollectorByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/collectors/{id}',
            path: {
                id: data.id
            }
        });
    }
    
}