// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginData, LoginResponse, GetProtectedResourceResponse, GetPublicResourceResponse } from './types.gen';

export class AuthControllerService {
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns AuthResponse OK
     * @throws ApiError
     */
    public static login(data: LoginData): CancelablePromise<LoginResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/auth/login',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
}

export class ResourceControllerService {
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getProtectedResource(): CancelablePromise<GetProtectedResourceResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/resource'
        });
    }
    
    /**
     * @returns string OK
     * @throws ApiError
     */
    public static getPublicResource(): CancelablePromise<GetPublicResourceResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/public/resource'
        });
    }
    
}