// This file is auto-generated by @hey-api/openapi-ts

/**
 * API Login and Authorization Request
 */
export type AuthRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

export type AuthResponse = {
    /**
     * JWT Authorization Token
     */
    token: string;
    /**
     * Username
     */
    username: string;
};

export type LoginData = {
    requestBody: AuthRequest;
};

export type LoginResponse = AuthResponse;

export type GetProtectedResourceResponse = {
    [key: string]: {
        [key: string]: unknown;
    };
};

export type GetPublicResourceResponse = {
    [key: string]: (string);
};

export type $OpenApiTs = {
    '/api/auth/login': {
        post: {
            req: LoginData;
            res: {
                /**
                 * OK
                 */
                200: AuthResponse;
            };
        };
    };
    '/api/resource': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: {
                    [key: string]: {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    '/api/public/resource': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: {
                    [key: string]: (string);
                };
            };
        };
    };
};